name: test composite action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo ref: ${{ github.ref }}
  composite-action: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${{ github.ref }}
      - id: composite
        uses: ./
